services:
    clickhouse:
        image: clickhouse/clickhouse-server:latest
        user: '101:101'
        container_name: clickhouse
        restart: unless-stopped
        hostname: clickhouse
        volumes:
            - ${PWD}/volumes/clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
            - ${PWD}/volumes/clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml
        ports:
            - '3218:8123/tcp'
            - '1238:9000/tcp'
        environment:
            - CLICKHOUSE_USER=clickhouse
            - CLICKHOUSE_PASSWORD=<YOUR_PASSWORD>
    grafana:
        image: grafana/grafana-enterprise:latest
        container_name: grafana
        restart: unless-stopped
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=<YOUR_PASSWORD>
            - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
            - GF_SECURITY_ALLOW_EMBEDDING=true
            - GF_SERVER_CERT_KEY=/etc/certs/privkey.pem
            - GF_SERVER_CERT_FILE=/etc/certs/fullchain.pem
            - GF_SERVER_PROTOCOL=https
        ports:
            - '5687:3000/tcp'
        volumes:
            - ${PWD}/volumes/grafana/:/etc/grafana/provisioning/datasources
            - /path/to/ssl/fullchain.pem:/etc/certs/fullchain.pem
            - /path/to/ssl/privkey.pem:/etc/certs/privkey.pem
        depends_on:
            - clickhouse