services:
    postgresql-master:
        image: bitnami/postgresql
        restart: unless-stopped
        ports:
            - '2345:5432/tcp'
        volumes:
            - /PATH/TO/POSTGRESQL_DATA:/bitnami/postgresql
        environment:
            - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
            - POSTGRESQL_LOG_HOSTNAME=true
            - POSTGRESQL_REPLICATION_MODE=master
            - POSTGRESQL_REPLICATION_USER=repl_user
            - POSTGRESQL_REPLICATION_PASSWORD=repl_user
            - POSTGRESQL_USERNAME=postgres
            - POSTGRESQL_PASSWORD=<YOUR_PASSWORD>
            - POSTGRESQL_DATABASE=development_database
            - ALLOW_EMPTY_PASSWORD=yes
